/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background":                 "#10131a",
        "surface":                    "#10131a",
        "surface-dim":                "#10131a",
        "surface-container-lowest":   "#0b0e14",
        "surface-container-low":      "#191c22",
        "surface-container":          "#1d2026",
        "surface-container-high":     "#272a31",
        "surface-container-highest":  "#32353c",
        "surface-bright":             "#363940",
        "surface-variant":            "#32353c",
        "on-surface":                 "#e1e2eb",
        "on-surface-variant":         "#c1c6d7",
        "on-background":              "#e1e2eb",
        "primary":                    "#00daf3",
        "primary-container":          "#009fb2",
        "primary-fixed":              "#9cf0ff",
        "primary-fixed-dim":          "#00daf3",
        "on-primary":                 "#00363d",
        "on-primary-container":       "#002f35",
        "on-primary-fixed":           "#001f24",
        "inverse-primary":            "#006875",
        "secondary":                  "#c3c6d1",
        "secondary-container":        "#454952",
        "secondary-fixed":            "#dfe2ee",
        "on-secondary":               "#2c3039",
        "on-secondary-container":     "#b5b8c3",
        "tertiary":                   "#4ae183",
        "tertiary-container":         "#00a657",
        "tertiary-fixed":             "#6bfe9c",
        "on-tertiary":                "#003919",
        "on-tertiary-container":      "#003115",
        "error":                      "#ffb4ab",
        "error-container":            "#93000a",
        "on-error":                   "#690005",
        "on-error-container":         "#ffdad6",
        "outline":                    "#8b90a0",
        "outline-variant":            "#414754",
        "inverse-surface":            "#e1e2eb",
        "inverse-on-surface":         "#2e3037",
        "surface-tint":               "#00daf3",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body:     ["Inter", "sans-serif"],
        label:    ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        "2xl":   "1rem",
        "3xl":   "1.5rem",
        full:    "9999px",
      },
    },
  },
  plugins: [],
};
